import copy
import json

def heal_gtm_container(gtm_json: dict, crawler_data: dict | None = None) -> dict:
    """
    Self-healing routine for GTM JSON exports.
    Automatically detects and fixes common schema violations to ensure successful import.
    """
    if "containerVersion" not in gtm_json:
        return gtm_json

    healed = copy.deepcopy(gtm_json)
    cv = healed["containerVersion"]
    
    tags = cv.get("tag", [])
    triggers = cv.get("trigger", [])
    variables = cv.get("variable", [])
    
    # ── 1. Fix Duplicate Names ───────────────────────────────────────────────
    # Identify items that were added in this session (AutoGTM managed)
    # We assume AutoGTM items have "Auto" in their name or are newly added tags/triggers
    
    # First, handle duplicate names but only if it's an AutoGTM item colliding with something else
    for item_array in [tags, triggers, variables]:
        seen_names = {}
        for item in item_array:
            name = item.get("name")
            if not name:
                continue
            
            # PROTECT: If it doesn't have "Auto" in name, skip healing/renaming
            if "Auto" not in name:
                continue

            if name in seen_names:
                seen_names[name] += 1
                item["name"] = f"{name} ({seen_names[name]})"
            else:
                seen_names[name] = 1

    # ── 1.5 Audit & Cleanup (The Clean-up) ────────────────────────────────────
    # Identify and pause generic Click triggers targeting "submit" or "Изпрати"
    # CRITICAL: Only pause if it's an AutoGTM-generated trigger!
    generic_submit_keywords = ["submit", "изпрати", "send", "запитване", "contact"]
    for trigger in triggers:
        if "Auto" not in trigger.get("name", ""):
            continue # PROTECT existing user triggers
            
        t_type = trigger.get("type", "")
        if t_type in ["CLICK", "LINK_CLICK", "click", "linkClick"]:
            filters = trigger.get("filter", [])
            is_generic = False
            for f in filters:
                param_type = f.get("type", "")
                if param_type in ["EQUALS", "CONTAINS", "MATCHES_CSS_SELECTOR"]:
                    for p in f.get("parameter", []):
                        val = str(p.get("value", "")).lower()
                        if any(kw in val for kw in generic_submit_keywords):
                            is_generic = True
                            break
            
            if is_generic:
                trigger["paused"] = True

    # ── 2. Fix Empty GA4 Measurement IDs ──────────────────────────────────────
    # Only fix tags that were generated by AutoGTM!
    fallback_ga_id = "G-HEALEDID00"
    for t in tags:
        if t.get("type") in ["googtag", "gaawc", "gaawe"]:
            for p in t.get("parameter", []):
                val = str(p.get("value", ""))
                if val.startswith("G-") and val != "G-HEALEDID00":
                    fallback_ga_id = val
                    break

    # If still placeholder, extract GA4 ID from crawler AJAX URLs
    if fallback_ga_id == "G-HEALEDID00" and crawler_data:
        import re
        for form in crawler_data.get("forms_processed", []):
            for ajax in form.get("ajax_responses", []):
                match = re.search(r'[?&]tid=(G-[A-Z0-9]+)', ajax.get("url", ""))
                if match:
                    fallback_ga_id = match.group(1)
                    break
            if fallback_ga_id != "G-HEALEDID00":
                break

    for tag in tags:
        # tagFiringOption is required for ALL tags (GTM may reject import without it)
        if not tag.get("tagFiringOption"):
            tag["tagFiringOption"] = "ONCE_PER_EVENT"

        # PROTECT: remaining fixes only for auto-injected tags
        if "Auto" not in tag.get("name", "") and "GA4 Event" not in tag.get("name", ""):
            continue

        if tag.get("type") == "gaawe":
            params = tag.get("parameter", [])
            has_override = False
            for p in params:
                if p.get("key") == "measurementIdOverride":
                    has_override = True
                    if not p.get("value") or p.get("value").strip() == "":
                        p["value"] = fallback_ga_id

            if not has_override:
                params.append({"type": "TEMPLATE", "key": "measurementIdOverride", "value": fallback_ga_id})

            # sign_up events should have 'method' parameter (GA4 recommended)
            event_name = next((p.get("value") for p in params if p.get("key") == "eventName"), None)
            if event_name and event_name.startswith("sign_up"):
                for p in params:
                    if p.get("key") == "eventSettingsTable":
                        has_method = any(
                            any(m.get("value") == "method" for m in row.get("map", []))
                            for row in p.get("list", [])
                        )
                        if not has_method:
                            p["list"].append({
                                "type": "MAP",
                                "map": [
                                    {"type": "TEMPLATE", "key": "parameter", "value": "method"},
                                    {"type": "TEMPLATE", "key": "parameterValue", "value": "form"}
                                ]
                            })
                        break

    # ── 3. Fix Trigger Required Parameters ────────────────────────────────────
    for trigger in triggers:
        # PROTECT: Only heal AutoGTM triggers
        if "Auto" not in trigger.get("name", ""):
            continue

        t_type = trigger.get("type", "")
        type_fixes = {
            "formSubmission": "FORM_SUBMISSION", "linkClick": "LINK_CLICK",
            "customEvent": "CUSTOM_EVENT", "pageview": "PAGEVIEW",
            "elementVisibility": "ELEMENT_VISIBILITY", "click": "CLICK"
        }
        if t_type in type_fixes:
            t_type = type_fixes[t_type]
            trigger["type"] = t_type
            
        params = trigger.get("parameter", [])
        existing_keys = {p.get("key") for p in params}

        if t_type in ["FORM_SUBMISSION", "LINK_CLICK"]:
            if "waitForTags" not in existing_keys:
                params.append({"type": "BOOLEAN", "key": "waitForTags", "value": "false"})
            if "checkValidation" not in existing_keys:
                params.append({"type": "BOOLEAN", "key": "checkValidation", "value": "false"})
        
        elif t_type == "ELEMENT_VISIBILITY":
            defaults = {
                "useOnScreenDuration": ("BOOLEAN", "true"),
                "minimumOnScreenDuration": ("INTEGER", "2000"),
                "useDomChangeListener": ("BOOLEAN", "true"),
                "firingFrequency": ("TEMPLATE", "ONCE_PER_PAGE"),
                "selectorType": ("TEMPLATE", "CSS"),
                "onScreenRatio": ("TEMPLATE", "10")
            }
            if "elementSelector" not in existing_keys:
                params.append({"type": "TEMPLATE", "key": "elementSelector", "value": "body"})
            
            for d_key, (d_type, d_val) in defaults.items():
                if d_key not in existing_keys:
                    params.append({"type": d_type, "key": d_key, "value": d_val})
        
        trigger["parameter"] = params

    # ── 4. Protect Custom Templates ───────────────────────────────────────────
    # We explicitly do NOT touch customTemplate array here. 
    # This ensure pre-existing templates remain intact regardless of healing.

    return healed
