import re
import json

with open("main.py", "r") as f:
    content = f.read()


HARVESTER_SCRIPT = """<script id="gtm-auto-harvester" type="text/javascript">
(function() {
  'use strict';
  // Array of field names generated by AutoGTM AI
  var payloadKeys = {{HARVESTER_KEYS}}; 

  function collectData(form) {
      if(!payloadKeys || payloadKeys.length === 0) return;
      var dataToStore = {};
      
      for(var i=0; i < payloadKeys.length; i++) {
          var key = payloadKeys[i];
          var el = form.querySelector('[name="' + key + '"]');
          if(el) {
              if (el.type === 'radio' || el.type === 'checkbox') {
                  var checkedEl = form.querySelector('[name="' + key + '"]:checked');
                  if (checkedEl) dataToStore[key] = checkedEl.value;
              } else {
                  dataToStore[key] = el.value;
              }
          }
      }
      
      if (Object.keys(dataToStore).length > 0) {
          sessionStorage.setItem('autogtm_payload', JSON.stringify(dataToStore));
      }
  }

  // Hook into form submits
  document.addEventListener('submit', function(e) {
      if(e.target && e.target.tagName === 'FORM') {
          collectData(e.target);
      }
  });

})();
</script>"""


# The logic goes into `main.py` right before saving the container to the output file.
# The easiest place is in `main()` just after `requires_ajax_listener` processing.

injection_code = f"""
        # Inject GTM Session Storage Harvester if non-AJAX payload keys are present
        requires_harvester = False
        harvester_keys = []
        for item in plan["tracking_plan"]:
            if item.get("trigger_type") in ["element_visibility", "page_view", "form_submission"]:
                keys = item.get("gtm_payload_keys", [])
                if keys:
                    requires_harvester = True
                    harvester_keys.extend(keys)

        if requires_harvester:
            unique_h_keys = list(set(harvester_keys))
            cv = updated_gtm.get("containerVersion", {{}})
            harvester_id = str(max([int(x.get("tagId", 0)) for x in cv.get("tag", []) if str(x.get("tagId", '0')).isdigit()] + [0]) + 1)
            account_id = cv.get("container", {{}}).get("accountId", "0")
            container_id = cv.get("container", {{}}).get("containerId", "0")
            
            # Prepare Custom JS variables to read from sessionStorage
            for k in unique_h_keys:
                cjs_name = f"CJS - Harvester - {{k}}"
                existing_vars = [v.get("name") for v in cv.get("variable", [])]
                if cjs_name not in existing_vars:
                    var_id = str(max([int(v.get("variableId", 0)) for v in cv.get("variable", []) if str(v.get("variableId", '0')).isdigit()] + [0]) + 1)
                    cjs_script = "function() {{ try {{ var data = JSON.parse(sessionStorage.getItem('autogtm_payload') || '{{}}'); return data['" + k + "'] || undefined; }} catch(e) {{ return undefined; }} }}"
                    cv["variable"].append({{
                        "accountId": account_id,
                        "containerId": container_id,
                        "variableId": var_id,
                        "name": cjs_name,
                        "type": "jsm",
                        "parameter": [
                            {{"type": "TEMPLATE", "key": "javascript", "value": cjs_script}}
                        ]
                    }})
                    print(f"  ++ Injected Custom JS Storage Variable for: {{k}} ++")

            # Inject Harvester Tag
            script_str = {json.dumps(HARVESTER_SCRIPT)}.replace("{{{{HARVESTER_KEYS}}}}", json.dumps(unique_h_keys))
            harvester_tag = {{
                "accountId": account_id,
                "containerId": container_id,
                "tagId": f"{{harvester_id}}000",
                "name": "Auto - Session Storage Harvester",
                "type": "html",
                "parameter": [
                    {{
                        "type": "TEMPLATE",
                        "key": "html",
                        "value": script_str
                    }}
                ],
                "firingTriggerId": ["2147479553"] # All Pages
            }}
            try:
                validated_harvester_tag = GtmTag(**harvester_tag).model_dump(exclude_none=True)
                cv.setdefault("tag", []).append(validated_harvester_tag)
                print(f"  ++ Injected Session Storage Harvester for {{len(unique_h_keys)}} fields ++")
            except ValidationError as e:
                print(f"Failed to inject Harvester listener: {{e}}")
"""

target = """            except ValidationError as e:
                print(f"Failed to inject AJAX listener: {e}")"""

new_content = content.replace(target, target + injection_code)


with open("main.py", "w") as f:
    f.write(new_content)

print("Patch applied to main.py to inject Session Storage Harvester successfully.")
